### ISSUE TITLE
Hash Mismatch: Cannot Compile using 2.18 on ARM Linux 

### ISSUE THREAD

**Issue by AMZN-Gene** [PopcornFX/O3DEPopcornFXPlugin#70] opened 2023-10-11 15:57 UTC
Building O3DE using PkFx fails to compile due to 2.18.0 zip hash not matching the hash found inside \Code\Platform\Linux\PAL_linux.cmake

**Repro Steps**
1. Set O3DEPopcornFxPlugin to point to commit 0825e25
2. Compile game

**Expected Results**
2.18.0 is downloaded and used successful by O3DE

*Actual Result**
Compiler error

```
[INFO] root: -- Downloading package into /home/ec2-user/.o3de/3rdParty/packages/PopcornFX-2.18.0-O3DE-linux-aarch64
[INFO] root: CMake Error at /home/ec2-user/o3de/cmake/3rdPartyPackages.cmake:287                                                   

[INFO] root:   ly_package: - Unable to get package PopcornFX-2.18.0-O3DE-linux-aarch64
[INFO] root:   from any download server.  Enable LY_PACKAGE_DEBUG to debug.

[INFO] root:   Error from server https://d3t6xeg4fgfoum.cloudfront.net - 22 - "HTTP
[INFO] root:   response code said error"

[INFO] root:   Error from server https://downloads.popcornfx.com/o3de-packages -1 -
[INFO] root:   Downloaded successfully, but the file hash did not match expected
``` 

**Dangerous Work Around**
If anyone is blocked from building, it's possible to remove HASH validation by deleting the validation python code.

_\o3de\cmake\3rdPartyPackages.cmake_
```
        if (NOT "${hash_of_downloaded_file}" STREQUAL "${download_file_internal_EXPECTED_HASH}" )
            set(results "1;Downloaded successfully, but the file hash did not match expected hash!")
            set(code_returned 1)
        endif()
```

**Comment by ValPKFX** [comment] 2023-10-11 17:04
Hi,
This was caused by a mistake in our release scripts.
This is fixed now and the hashes will be correct in future releases.
I pushed the correct hash for 2.18.0 on the development branch in the commit [401b4c7](https://github.com/PopcornFX/O3DEPopcornFXPlugin/commit/401b4c7cba0089c814ebe0b606b5d967740a9335).
Thank you for reporting it.

**Closed** 2023-10-17 08:03 UTC
